version: '2'
services:
  mongodb:
    image: mongo:latest
    volumes:
      - './data/mongodb:/data/db'
    restart: always
    ports:
      - '27017:27017'

  elasticsearch:
    build:
      context: 'elasticsearch/'
    volumes:
      - './data/elasticsearch:/usr/share/elasticsearch/data'
    restart: always
    ports:
      - '9200:9200'
      - '9300:9300'

  # elasticsearch-v2:
  #   build:
  #     context: 'elasticsearch-v2/'
  #   volumes:
  #     - './data/elasticsearch-v2:/usr/share/elasticsearch/data'
  #   restart: always
  #   ports:
  #     - '9201:9200'
  #     - '9301:9300'

  redis:
    image: redis:latest
    ports:
      - '6379:6379'

  plantuml:
    image: plantuml/plantuml-server:latest
    ports:
      - '8080:8080'
